# Лабораторная работа №4

**Цель работы**: "".

**Ход работы**:

## Задание 1

**Пункт 1**. Напишите программу для решения примера (по вариантам). Предусмотрите проверку деления на ноль. Все необходимые переменные пользователь вводит через консоль. Запись |пример| означает <<взять по модулю>>, т. е. если значение получится отрицательным, необходимо сменить знак с минуса на плюс.

**Вариант 1**. $|{ {({a^2 \over b^2} + c^2 \cdot a^2)} \over {(a + b + c \cdot (k- {a \over b^3}))} } + c + ({k \over b} - {k \over a}) \cdot c|$

In [1]:
import math

def task111(a, b, c, k):
    if a == 0:
        print("a = 0. Error: div on zero")
        return -1
    elif b == 0:
        print("b = 0. Error: div on zero")
        return -1
    else:
        part1 = math.pow(a, 2) / math.pow(b, 2) + math.pow(c, 2) * math.pow(a, 2)
        part2 = a + b + c * (k - a / math.pow(b, 3))
        part3 = c + (k/b - k/a) * c
        result = part1 + part2 + part3
        if result >= 0:
            return result
        else:
            return -result

def task111_main():

    print(
        """
    Задание 1

    1. Напишите программу для решения примера (по вариантам). Предусмотрите проверку деления на ноль. Все необходимые переменные пользователь вводит через консоль. Запись |пример| означает <<взять по модулю>>, т. е. если значение получится отрицательным, необходимо сменить знак с минуса на плюс.

    Вариант 1. |a^2 / b^2} + c^2 * a^2) / (a + b + c * (k - a / b^3)) + c + ({k / b} - k / a) * c|$
        """
    )

    a = int(input("a := "))
    b = int(input("b := "))
    c = int(input("c := "))
    k = int(input("k := "))
    print(task111(a,b,c,k))

task111_main()


    Задание 1

    1. Напишите программу для решения примера (по вариантам). Предусмотрите проверку деления на ноль. Все необходимые переменные пользователь вводит через консоль. Запись |пример| означает <<взять по модулю>>, т. е. если значение получится отрицательным, необходимо сменить знак с минуса на плюс.

    Вариант 1. |a^2 / b^2} + c^2 * a^2) / (a + b + c * (k - a / b^3)) + c + ({k / b} - k / a) * c|$
        
a := 1
b := 1
c := 1
k := 1
5.0


## Задание 1

**Пункт 2**. Дан произвольный список, содержащий и строки и числа.

**Вариант 1**. Выведите все четные элементы построчно.

In [2]:
def task121(lst):
    for i in range(len(lst)):
        if (i + 1) % 2 == 0:
            print(lst[i])

def task121_main():
    print(
        """
Задание 1

2. Дан произвольный список, содержащий и строки и числа.

Вариант 1. Выведите все четные элементы построчно.
        """
    )
    lst = ['33', 2, 4, 5.3, 2.4, 5555.3, '443', 'ergr', 'wee', 'efe']
    print(lst)
    task121(lst)

task121_main()


Задание 1

2. Дан произвольный список, содержащий и строки и числа.

Вариант 1. Выведите все четные элементы построчно.
        
['33', 2, 4, 5.3, 2.4, 5555.3, '443', 'ergr', 'wee', 'efe']
2
5.3
5555.3
ergr
efe


## Задание 1

**Пункт 3**. Дан произвольный список, содержащий только числа.

**Вариант 1**. Выведите результат сложения всех чисел больше 10.

In [3]:
def task131(lst):
    sum = 0
    for i in range(len(lst)):
        if lst[i] > 10:
            sum += lst[i]
    print(sum)
    


def task131_main():
    print(
        """
Задание 1

Пункт 3. Дан произвольный список, содержащий только числа.

Вариант 1. Выведите результат сложения всех чисел больше 10.
        """
    )
    lst = [-10, 5, 6, 15, 3, 16, 7]
    print(lst)
    task131(lst)

task131_main()


Задание 1

Пункт 3. Дан произвольный список, содержащий только числа.

Вариант 1. Выведите результат сложения всех чисел больше 10.
        
[-10, 5, 6, 15, 3, 16, 7]
31


## Задание 1

**Пункт 4**. Дан произвольный список, содержащий только числа.

**Вариант 1**. Выведите максимальное число.

In [4]:
def task141(lst):
    max = lst[0]
    for i in range(len(lst)):
        if lst[i] > max:
            max = lst[i]
    print(max)
    
def task141_main():
    print(
        """
Задание 1

4. Дан произвольный список, содержащий только числа.

Вариант 1. Выведите максимальное число.
        """
    )
    lst = [4, 7, 2, -100, 3, 55, 33, 6]
    print(lst)
    task141(lst)

task141_main()


Задание 1

4. Дан произвольный список, содержащий только числа.

Вариант 1. Выведите максимальное число.
        
[4, 7, 2, -100, 3, 55, 33, 6]
55


## Задание 2 "Строки и списки"

**Пункт 1**. Пусть задано некоторое число `my_number`. Пользователь вводит с клавиатуры свое число `user_number`.

**Вариант 1**. Запрашивайте у пользователя вводить число `user_number` до тех пор, пока оно не будет меньше `my_number`.

In [5]:
def task211():
    my_number = 5
    print("my_number = %d" % my_number)
    
    while 1:
        user_number = int(input("user_number := "))
        if user_number < my_number:
            break

def task211_main():
    print(
        """
Задание 2 "Строки и списки"

1. Пусть задано некоторое число my_number. Пользователь вводит с клавиатуры свое число user_number.

Вариант 1. Запрашивайте у пользователя вводить число user_number до тех пор, пока оно не будет меньше my_number.
        """
    )

    task211()

task211_main()


Задание 2 "Строки и списки"

1. Пусть задано некоторое число my_number. Пользователь вводит с клавиатуры свое число user_number.

Вариант 1. Запрашивайте у пользователя вводить число user_number до тех пор, пока оно не будет меньше my_number.
        
my_number = 5
user_number := 77
user_number := 55
user_number := 5
user_number := 2


## Задание 2 "Строки и списки"

**Пункт 2**. Пусть задан список, содержащий строки.

**Вариант 1**. Выведите построчно все строки размером от 5 до 10 символов.

In [6]:
def task221(lst):
    for i in range(len(lst)):
        length = len(lst[i])
        if 5 < length and length < 10:
            print(lst[i])

def task221_main():
    print(
        """
Задание 2 "Строки и списки"

2. Пусть задан список, содержащий строки.

Вариант 1. Выведите построчно все строки размером от 5 до 10 символов.
        """
    )

    lst = [
        'aaa',
        'bbbbbb',
        'ccccc',
        'dddddddddd',
        'eeeeeeeee'
    ]

    task221(lst)

task221_main()


Задание 2 "Строки и списки"

2. Пусть задан список, содержащий строки.

Вариант 1. Выведите построчно все строки размером от 5 до 10 символов.
        
bbbbbb
eeeeeeeee


## Задание 2 "Строки и списки"

**Пункт 3**. Сгенерируйте и выведите:

**Вариант 1**. Случайную строку, состоящую из 5 символов, содержащую только заглавные буквы русского алфавита.

In [7]:
import random

def task231():
    result = ''
    for i in range(5):
        number = random.randint(65, 90)
        symbol = chr(number)
        result += symbol
    return result

def task231_main():
    print(
        """
Задание 2 "Строки и списки"

3. Сгенерируйте и выведите:

Вариант 1. Случайную строку, состоящую из 5 символов, содержащую только заглавные буквы русского алфавита.
        """
    )

    print(task231())

task231_main()


Задание 2 "Строки и списки"

3. Сгенерируйте и выведите:

Вариант 1. Случайную строку, состоящую из 5 символов, содержащую только заглавные буквы русского алфавита.
        
SRWYN


## Задание 2 "Строки и списки"

**Пункт 4**. Пусть дана строка:

**Вариант 1**. На основе данной строки сформируйте новую, содержащую только цифры. Выведите новую строку.

In [8]:
def task241(string):
    res = ''
    for i in range(len(string)):
        res += str(ord(string[i]))
    return res

def task241_main():
    print(
        """
Задание 2 "Строки и списки"

4. Пусть дана строка:

Вариант 1. На основе данной строки сформируйте новую, содержащую только цифры. Выведите новую строку.
        """
    )

    print(task241('qwerty'))

task241_main()


Задание 2 "Строки и списки"

4. Пусть дана строка:

Вариант 1. На основе данной строки сформируйте новую, содержащую только цифры. Выведите новую строку.
        
113119101114116121


## Задание 3 "Матрицы"

Пусть дана матрица:

```bash
1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2
```

**Вариант №1**. Определите структуру для хранения матрицы.

**Пункт 1**. Напишите функцию возведения всех элементов матрицы в квадрат.

In [9]:
import math
import numpy

def task311(arr):
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            arr[i][j] = math.pow(arr[i][j], 2)
 


def task311_main():
    print(
        """
Задание 3 "Матрицы"

Пусть дана матрица:

1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2

Вариант №1. Определите структуру для хранения матрицы.

1. Напишите функцию возведения всех элементов матрицы в квадрат.
        """
    )

    arr = numpy.array([
        [1, 2, 3, 4, 5, 6, 7, 8],
        [8, 7, 6, 5, 4, 3, 2, 1],
        [2, 3, 4, 5, 6, 7, 8, 9],
        [9, 8, 7, 6, 5, 4, 3, 2],
        [1, 3, 5, 7, 9, 7, 5, 3],
        [3, 1, 5, 3, 2, 6, 5, 7],
        [1, 7, 5, 9, 7, 3, 1, 5],
        [2, 6, 3, 5, 1, 7, 3, 2]
    ])

    print(arr)
    print()
    task311(arr)
    print(arr)

task311_main()


Задание 3 "Матрицы"

Пусть дана матрица:

1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2

Вариант №1. Определите структуру для хранения матрицы.

1. Напишите функцию возведения всех элементов матрицы в квадрат.
        
[[1 2 3 4 5 6 7 8]
 [8 7 6 5 4 3 2 1]
 [2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2]
 [1 3 5 7 9 7 5 3]
 [3 1 5 3 2 6 5 7]
 [1 7 5 9 7 3 1 5]
 [2 6 3 5 1 7 3 2]]

[[ 1  4  9 16 25 36 49 64]
 [64 49 36 25 16  9  4  1]
 [ 4  9 16 25 36 49 64 81]
 [81 64 49 36 25 16  9  4]
 [ 1  9 25 49 81 49 25  9]
 [ 9  1 25  9  4 36 25 49]
 [ 1 49 25 81 49  9  1 25]
 [ 4 36  9 25  1 49  9  4]]


## Задание 3 "Матрицы"

Пусть дана матрица:

```bash
1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2
```

**Вариант №2**. Определите структуру для хранения матрицы.

**Пункт 1.** Напишите функцию сложения по строкам.

In [10]:
def task321(arr):
    for i in range(len(arr)):
        sum = 0
        for j in range(len(arr[i])):
            sum += arr[i][j]
            print("%4d\t" % arr[i][j], end = '')
        print(sum)
        
def task321_main():
    print(
        """
Задание 3 "Матрицы"

Пусть дана матрица:

1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2

Вариант №2. Определите структуру для хранения матрицы.

1. Напишите функцию сложения по строкам.
        """
    )

    arr = [
        [1, 2, 3, 4, 5, 6, 7, 8],
        [8, 7, 6, 5, 4, 3, 2, 1],
        [2, 3, 4, 5, 6, 7, 8, 9],
        [9, 8, 7, 6, 5, 4, 3, 2],
        [1, 3, 5, 7, 9, 7, 5, 3],
        [3, 1, 5, 3, 2, 6, 5, 7],
        [1, 7, 5, 9, 7, 3, 1, 5],
        [2, 6, 3, 5, 1, 7, 3, 2]
    ]

    task321(arr)

task321_main()


Задание 3 "Матрицы"

Пусть дана матрица:

1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2

Вариант №2. Определите структуру для хранения матрицы.

1. Напишите функцию сложения по строкам.
        
   1	   2	   3	   4	   5	   6	   7	   8	36
   8	   7	   6	   5	   4	   3	   2	   1	36
   2	   3	   4	   5	   6	   7	   8	   9	44
   9	   8	   7	   6	   5	   4	   3	   2	44
   1	   3	   5	   7	   9	   7	   5	   3	40
   3	   1	   5	   3	   2	   6	   5	   7	32
   1	   7	   5	   9	   7	   3	   1	   5	38
   2	   6	   3	   5	   1	   7	   3	   2	29


## Задание 3 "Матрицы"

Пусть дана матрица:

```bash
1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2
```

**Вариант №4**. Определите структуру для хранения матрицы.

**Пункт 1.** Напишите функцию умножения по строкам.

In [11]:
def task341(arr):
    for i in range(len(arr)):
        mult = 1
        for j in range(len(arr[i])):
            mult *= arr[i][j]
            print("%4d\t" % arr[i][j], end = '')
        print(mult)
        
def task341_main():
    print(
        """
Задание 3 "Матрицы"

Пусть дана матрица:

1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2

Вариант №4. Определите структуру для хранения матрицы.

1. Напишите функцию умножения по строкам.
        """
    )

    arr = [
        [1, 2, 3, 4, 5, 6, 7, 8],
        [8, 7, 6, 5, 4, 3, 2, 1],
        [2, 3, 4, 5, 6, 7, 8, 9],
        [9, 8, 7, 6, 5, 4, 3, 2],
        [1, 3, 5, 7, 9, 7, 5, 3],
        [3, 1, 5, 3, 2, 6, 5, 7],
        [1, 7, 5, 9, 7, 3, 1, 5],
        [2, 6, 3, 5, 1, 7, 3, 2]
    ]

    task341(arr)   

task341_main()


Задание 3 "Матрицы"

Пусть дана матрица:

1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2

Вариант №4. Определите структуру для хранения матрицы.

1. Напишите функцию умножения по строкам.
        
   1	   2	   3	   4	   5	   6	   7	   8	40320
   8	   7	   6	   5	   4	   3	   2	   1	40320
   2	   3	   4	   5	   6	   7	   8	   9	362880
   9	   8	   7	   6	   5	   4	   3	   2	362880
   1	   3	   5	   7	   9	   7	   5	   3	99225
   3	   1	   5	   3	   2	   6	   5	   7	18900
   1	   7	   5	   9	   7	   3	   1	   5	33075
   2	   6	   3	   5	   1	   7	   3	   2	7560


## Задание 3 "Матрицы"

Пусть дана матрица:

```bash
1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2
```

**Вариант №5**. Определите структуру для хранения матрицы.

**Пункт 3**. Напишите функцию возведения всех чисел 5 в квадрат.

In [12]:
import numpy

def task353(arr):
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            if arr[i][j] == 5:
                arr[i][j] = 25

def task353_main():
    print(
        """
Задание 3 "Матрицы"

Пусть дана матрица:

1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2

Вариант №5. Определите структуру для хранения матрицы.

3. Напишите функцию возведения всех чисел 5 в квадрат.
        """
    )

    arr = numpy.array([
        [1, 2, 3, 4, 5, 6, 7, 8],
        [8, 7, 6, 5, 4, 3, 2, 1],
        [2, 3, 4, 5, 6, 7, 8, 9],
        [9, 8, 7, 6, 5, 4, 3, 2],
        [1, 3, 5, 7, 9, 7, 5, 3],
        [3, 1, 5, 3, 2, 6, 5, 7],
        [1, 7, 5, 9, 7, 3, 1, 5],
        [2, 6, 3, 5, 1, 7, 3, 2]
    ])

    print(arr)
    print()
    task353(arr)
    print(arr)  

task353_main()


Задание 3 "Матрицы"

Пусть дана матрица:

1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2

Вариант №5. Определите структуру для хранения матрицы.

3. Напишите функцию возведения всех чисел 5 в квадрат.
        
[[1 2 3 4 5 6 7 8]
 [8 7 6 5 4 3 2 1]
 [2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2]
 [1 3 5 7 9 7 5 3]
 [3 1 5 3 2 6 5 7]
 [1 7 5 9 7 3 1 5]
 [2 6 3 5 1 7 3 2]]

[[ 1  2  3  4 25  6  7  8]
 [ 8  7  6 25  4  3  2  1]
 [ 2  3  4 25  6  7  8  9]
 [ 9  8  7  6 25  4  3  2]
 [ 1  3 25  7  9  7 25  3]
 [ 3  1 25  3  2  6 25  7]
 [ 1  7 25  9  7  3  1 25]
 [ 2  6  3 25  1  7  3  2]]


## Задание 3 "Матрицы"

Пусть дана матрица:

```bash
1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2
```

**Вариант №6**. Определите структуру для хранения матрицы.

**Пункт 3**. Напишите функцию очистки матрицы.

In [13]:
import numpy

def task363(arr):
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            arr[i][j] = 0

def task363_main():
    print(
        """
Задание 3 "Матрицы"

Пусть дана матрица:

1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2

Вариант №6. Определите структуру для хранения матрицы.

3. Напишите функцию очистки матрицы.

        """
    )

    arr = numpy.array([
        [1, 2, 3, 4, 5, 6, 7, 8],
        [8, 7, 6, 5, 4, 3, 2, 1],
        [2, 3, 4, 5, 6, 7, 8, 9],
        [9, 8, 7, 6, 5, 4, 3, 2],
        [1, 3, 5, 7, 9, 7, 5, 3],
        [3, 1, 5, 3, 2, 6, 5, 7],
        [1, 7, 5, 9, 7, 3, 1, 5],
        [2, 6, 3, 5, 1, 7, 3, 2]
    ])

    print(arr)
    print()
    task363(arr)
    print(arr)

task363_main()


Задание 3 "Матрицы"

Пусть дана матрица:

1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2

Вариант №6. Определите структуру для хранения матрицы.

3. Напишите функцию очистки матрицы.

        
[[1 2 3 4 5 6 7 8]
 [8 7 6 5 4 3 2 1]
 [2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2]
 [1 3 5 7 9 7 5 3]
 [3 1 5 3 2 6 5 7]
 [1 7 5 9 7 3 1 5]
 [2 6 3 5 1 7 3 2]]

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


## Задание 3 "Матрицы"

Пусть дана матрица:

```bash
1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2
```

**Вариант №7**. Определите структуру для хранения матрицы.

**Пункт 3**. Напишите функцию, которая посчитает, сколько раз в матрице встречается число 3

In [14]:
import numpy

def task373(arr):
    sum = 0
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            if arr[i][j] == 3:
                sum += 1
    return sum

def task373_main():
    print(
        """
Задание 3 "Матрицы"

Пусть дана матрица:

1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2

Вариант №7. Определите структуру для хранения матрицы.

3. Напишите функцию, которая посчитает, сколько раз в матрице встречается число 3
        """
    )

    arr = numpy.array([
        [1, 2, 3, 4, 5, 6, 7, 8],
        [8, 7, 6, 5, 4, 3, 2, 1],
        [2, 3, 4, 5, 6, 7, 8, 9],
        [9, 8, 7, 6, 5, 4, 3, 2],
        [1, 3, 5, 7, 9, 7, 5, 3],
        [3, 1, 5, 3, 2, 6, 5, 7],
        [1, 7, 5, 9, 7, 3, 1, 5],
        [2, 6, 3, 5, 1, 7, 3, 2]
    ])

    print(arr)
    print()
    print("emount element = 3: %d" % task373(arr))

task373_main()


Задание 3 "Матрицы"

Пусть дана матрица:

1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2

Вариант №7. Определите структуру для хранения матрицы.

3. Напишите функцию, которая посчитает, сколько раз в матрице встречается число 3
        
[[1 2 3 4 5 6 7 8]
 [8 7 6 5 4 3 2 1]
 [2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2]
 [1 3 5 7 9 7 5 3]
 [3 1 5 3 2 6 5 7]
 [1 7 5 9 7 3 1 5]
 [2 6 3 5 1 7 3 2]]

emount element = 3: 11


## Задание 3 "Матрицы"

Пусть дана матрица:

```bash
1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2
```

**Вариант №8**. Определите структуру для хранения матрицы.

**Пункт 1**. Пусть пользователь через консоль вводит два числа: первое - номер строки, второе - номер столбца. Напишите функцию, которая найдет число в данной позиции.

In [15]:
import numpy

def task381(arr, i, j):
    if i > len(arr):
        return 0
    elif j > len(arr[i]):
        return 0
    else:
        return arr[i - 1][j - 1]

def task381_main():
    print(
        """
Задание 3 "Матрицы"

Пусть дана матрица:

1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2

Вариант №8. Определите структуру для хранения матрицы.

1. Пусть пользователь через консоль вводит два числа: первое - номер строки, второе - номер столбца. Напишите функцию, которая найдет число в данной позиции.
        """
    )

    arr = numpy.array([
        [1, 2, 3, 4, 5, 6, 7, 8],
        [8, 7, 6, 5, 4, 3, 2, 1],
        [2, 3, 4, 5, 6, 7, 8, 9],
        [9, 8, 7, 6, 5, 4, 3, 2],
        [1, 3, 5, 7, 9, 7, 5, 3],
        [3, 1, 5, 3, 2, 6, 5, 7],
        [1, 7, 5, 9, 7, 3, 1, 5],
        [2, 6, 3, 5, 1, 7, 3, 2]
    ])

    print(arr)
    print()
    print("arr[%d][%d] = %d" % (-3, -3, task381(arr, -3, -3)))
    print("arr[%d][%d] = %d" % (-2, -2, task381(arr, -2, -2)))
    print("arr[%d][%d] = %d" % (-1, -1, task381(arr, -1, -1)))
    print("arr[%d][%d] = %d" % (0, 0, task381(arr, 0, 0)))
    print()
    print("arr[%d][%d] = %d" % (4, 4, task381(arr, 4, 4)))
    print("arr[%d][%d] = %d" % (40, 4, task381(arr, 40, 4)))
    print("arr[%d][%d] = %d" % (4, 40, task381(arr, 4, 40)))

task381_main()


Задание 3 "Матрицы"

Пусть дана матрица:

1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2

Вариант №8. Определите структуру для хранения матрицы.

1. Пусть пользователь через консоль вводит два числа: первое - номер строки, второе - номер столбца. Напишите функцию, которая найдет число в данной позиции.
        
[[1 2 3 4 5 6 7 8]
 [8 7 6 5 4 3 2 1]
 [2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2]
 [1 3 5 7 9 7 5 3]
 [3 1 5 3 2 6 5 7]
 [1 7 5 9 7 3 1 5]
 [2 6 3 5 1 7 3 2]]

arr[-3][-3] = 9
arr[-2][-2] = 6
arr[-1][-1] = 1
arr[0][0] = 2

arr[4][4] = 6
arr[40][4] = 0
arr[4][40] = 0


## Задание 4 "Строки"

1. Пусть дана строка, состоящая из слов, пробелов и знаков препинания. На основании этой строки создайте новую (и выведите ее на консоль):

**Вариант 1**. Содержащую только слова больше 5 символов. Разделитель слов в строке - пробел.

In [16]:
def task411(string):
    strList = string.split()
    result = ''
    for word in strList:
        if len(word) > 5:
            result += word + ' '
    return result

def task411_main():
    print(
        """
Задание 4 "Строки"

1. Пусть дана строка, состоящая из слов, пробелов и знаков препинания. На основании этой строки создайте новую (и выведите ее на консоль):

Вариант 1. Содержащую только слова больше 5 символов. Разделитель слов в строке - пробел.
        """
    )

    str = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quisquam vitae distinctio rem eum quam velit cum ab voluptatum quas quaerat, nisi corporis suscipit odio? Autem possimus voluptatem rerum culpa animi veniam fugit illum? Asperiores odit aliquid aperiam nobis itaque expedita tenetur iste aliquam ea inventore recusandae eos, cum, corporis ab iusto. Velit nulla tenetur ut minima fugiat aperiam cupiditate dignissimos tempora enim! Dicta esse explicabo reprehenderit repellat numquam exercitationem suscipit asperiores ab velit deleniti adipisci eaque placeat, sapiente eos officia debitis, delectus provident voluptas nesciunt ratione veniam? Tenetur provident officia ipsum rem doloremque impedit aliquid. Amet maiores obcaecati ratione cum!"

    print(str)
    print()
    print(task411(str))

task411_main()


Задание 4 "Строки"

1. Пусть дана строка, состоящая из слов, пробелов и знаков препинания. На основании этой строки создайте новую (и выведите ее на консоль):

Вариант 1. Содержащую только слова больше 5 символов. Разделитель слов в строке - пробел.
        
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quisquam vitae distinctio rem eum quam velit cum ab voluptatum quas quaerat, nisi corporis suscipit odio? Autem possimus voluptatem rerum culpa animi veniam fugit illum? Asperiores odit aliquid aperiam nobis itaque expedita tenetur iste aliquam ea inventore recusandae eos, cum, corporis ab iusto. Velit nulla tenetur ut minima fugiat aperiam cupiditate dignissimos tempora enim! Dicta esse explicabo reprehenderit repellat numquam exercitationem suscipit asperiores ab velit deleniti adipisci eaque placeat, sapiente eos officia debitis, delectus provident voluptas nesciunt ratione veniam? Tenetur provident officia ipsum rem doloremque impedit aliquid. Amet maiores obcaecati rat

## Задание 4 "Строки"

**Пункт 2.**. Пусть дана строковая переменная, содержащая информацию о студентах:

```python
my_string = 'Ф;И;О;Возраст;Категория;_Иванов;Иван;Иванович;23 года;Студент 3 курса;_Петров;Семен;Игоревич;22 года;Студент 2 курса'
```

**Вариант 1**. Выведите информацию в виде:

```
Ф И О                    Категория          Возраст
Иванов Иван Иванович     Студент 3 курса    23 года
Петров Семен Игоревич    Студент 2 курса    22 года
```

In [17]:
def task421(string):
    arr = string.split('_')
    for i in range(len(arr)):
        arr[i] = arr[i].split(';')
        name = arr[i][0]
        surname = arr[i][1]
        middlename = arr[i][2]
        age = arr[i][3]
        category = arr[i][4]
        
        name_surname_middlename = name + ' ' + surname + ' ' + middlename
        
        print("%-36s\t%-16s\t%-12s" % (name_surname_middlename, category, age))

def task421_main():
    print(
        """
Задание 4 "Строки"

Пункт 2. Пусть дана строковая переменная, содержащая информацию о студентах:

my_string = 'Ф;И;О;Возраст;Категория;_Иванов;Иван;Иванович;23 года;Студент 3 курса;_Петров;Семен;Игоревич;22 года;Студент 2 курса'

Вариант 1. Выведите информацию в виде:

Ф И О                    Категория          Возраст
Иванов Иван Иванович     Студент 3 курса    23 года
Петров Семен Игоревич    Студент 2 курса    22 года
        """
    )

    my_string = 'Ф;И;О;Возраст;Категория;_Иванов;Иван;Иванович;23 года;Студент 3 курса;_Петров;Семен;Игоревич;22 года;Студент 2 курса'

    task421(my_string)

task421_main()


Задание 4 "Строки"

Пункт 2. Пусть дана строковая переменная, содержащая информацию о студентах:

my_string = 'Ф;И;О;Возраст;Категория;_Иванов;Иван;Иванович;23 года;Студент 3 курса;_Петров;Семен;Игоревич;22 года;Студент 2 курса'

Вариант 1. Выведите информацию в виде:

Ф И О                    Категория          Возраст
Иванов Иван Иванович     Студент 3 курса    23 года
Петров Семен Игоревич    Студент 2 курса    22 года
        
Ф И О                               	Категория       	Возраст     
Иванов Иван Иванович                	Студент 3 курса 	23 года     
Петров Семен Игоревич               	Студент 2 курса 	22 года     


## Задание 4 "Строки"

**Пункт 3**. Пусть дана строковая переменная, содержащая информацию о студентах вида:

```python
my_string = 'ФИО;Возраст,Категория; Иванов Иван Иванович;23 года, Студент 3 курса; Петров Семен Игоревич, 22 года;Студент 2 курса: Иванов Семен Игоревич, 22 года, Студент 2 курса;_Акимов Ярослав Наумович;23 года;Студент 3 курса; Борков Станислав Максимович;21 год;Студент 1 курса; Петров Семен Семенович;21 год;Студент 1 курса;_Романов Станислав Андреевич, 23 года, Студент 3 курса; Петров Всеволод Борисович;21 год;Студент 2 курса'
```

**Вариант 1**. Выведите построчно информацию о студентах, чья фамилия 'Петров'.

In [18]:
def task431(string):
    arr = string.split('_')
    
    for i in range(len(arr)):
        arr[i] = arr[i].split(';')
        surname = arr[i][0]
        name = arr[i][1]
        middlename = arr[i][2]
        age = arr[i][3]
        category = arr[i][4]
        
        name_surname_middlename = name + ' ' + surname + ' ' + middlename
        
        if surname == 'Петров':
            print(surname)
            print(name)
            print(middlename)
            print(age)
            print(category)
            print()
            #print("%12s\t%12s\t%12s\t%12s\t%16s" % (surname, name, middlename, age, category))

def task431_main():
    print(
        """
Задание 4 "Строки"

3. Пусть дана строковая переменная, содержащая информацию о студентах вида:

my_string = 'ФИО;Возраст,Категория; Иванов Иван Иванович;23 года, Студент 3 курса; Петров Семен Игоревич, 22 года;Студент 2 курса: Иванов Семен Игоревич, 22 года, Студент 2 курса;_Акимов Ярослав Наумович;23 года;Студент 3 курса; Борков Станислав Максимович;21 год;Студент 1 курса; Петров Семен Семенович;21 год;Студент 1 курса;_Романов Станислав Андреевич, 23 года, Студент 3 курса; Петров Всеволод Борисович;21 год;Студент 2 курса'

Вариант 1. Выведите построчно информацию о студентах, чья фамилия 'Петров'.
        """
    )

    my_string = 'Ф;И;О;Возраст;Категория;_Иванов;Иван;Иванович;23 года;Студент 3 курса;_Петров;Семен;Игоревич;22 года;Студент 2 курса'

    task431(my_string)

task431_main()


Задание 4 "Строки"

3. Пусть дана строковая переменная, содержащая информацию о студентах вида:

my_string = 'ФИО;Возраст,Категория; Иванов Иван Иванович;23 года, Студент 3 курса; Петров Семен Игоревич, 22 года;Студент 2 курса: Иванов Семен Игоревич, 22 года, Студент 2 курса;_Акимов Ярослав Наумович;23 года;Студент 3 курса; Борков Станислав Максимович;21 год;Студент 1 курса; Петров Семен Семенович;21 год;Студент 1 курса;_Романов Станислав Андреевич, 23 года, Студент 3 курса; Петров Всеволод Борисович;21 год;Студент 2 курса'

Вариант 1. Выведите построчно информацию о студентах, чья фамилия 'Петров'.
        
Петров
Семен
Игоревич
22 года
Студент 2 курса



## Задание 4 "Строки"

**Пункт 4**. Пусть дана строка произвольной длины. Выведите информацию о том, сколько в ней символов и сколько слов.

In [19]:
def task44(string):
    counter = 0
    for i in string:
        counter += 1
    print('number symbols: %d' % counter)
    
    words = string.split()
    print("number words: %d" % len(words))

def task44_main():
    print(
        """
Задание 4 "Строки"

4. Пусть дана строка произвольной длины. Выведите информацию о том, сколько в ней символов и сколько слов.
        """
    )

    string = 'Далеко-далеко за словесными горами в стране гласных и согласных живут рыбные тексты.'

    print(string)
    print()
    task44(string)

task44_main()


Задание 4 "Строки"

4. Пусть дана строка произвольной длины. Выведите информацию о том, сколько в ней символов и сколько слов.
        
Далеко-далеко за словесными горами в стране гласных и согласных живут рыбные тексты.

number symbols: 84
number words: 12


## Задание 6 "Списки"

**Пункт 1**. Пусть дана матрица чисел размером `NxN`, Представьте данную матрицу в виде списка. Выведите результат сложения всех элементов матрицы.

In [20]:
def task61(arr):
    lst = []
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            lst.append(arr[i][j])
    sum = 0
    for i in range(len(lst)):
        sum += lst[i]
    return sum

def task61_main():
    print(
        """
Задание 6 "Списки"

1. Пусть дана матрица чисел размером NxN, Представьте данную матрицу в виде списка. Выведите результат сложения всех элементов матрицы.
        """
    )

    arr = [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
        [13, 14, 15, 16]
    ]

    print(task61(arr))

task61_main()


Задание 6 "Списки"

1. Пусть дана матрица чисел размером NxN, Представьте данную матрицу в виде списка. Выведите результат сложения всех элементов матрицы.
        
136


## Задание 6 "Списки"

**Пункт 2**. Пусть дан список из 10 элементов.

**Вариант 1**. Удалите первые 2 элемента и добавьте 2 новых. Выведите список на экран.

In [21]:
def task621(lst, addedLst):
    for i in range(len(addedLst)):
        lst.pop(0)
    for i in range(len(addedLst) - 1, -1, -1):
        lst.insert(0, addedLst[i])
    return lst

def task621_main():
    print(
        """
Задание 6 "Списки"

2. Пусть дан список из 10 элементов.

Вариант 1. Удалите первые 2 элемента и добавьте 2 новых. Выведите список на экран.
        """
    )

    lst = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    print(lst)
    addedLst = [111, 222]
    print(addedLst)
    lst = task621(lst, addedLst)
    print(lst)

task621_main()


Задание 6 "Списки"

2. Пусть дан список из 10 элементов.

Вариант 1. Удалите первые 2 элемента и добавьте 2 новых. Выведите список на экран.
        
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[111, 222]
[111, 222, 3, 4, 5, 6, 7, 8, 9]


## Задание 6 "Списки"

**Пункт 3**. Пусть журнал по предмету "Информационные технологии" представлен в виде списка: 

```python
my_len = [
    ['БО-331101', ['Акулова Алена', 'Бабушкина Ксения', ...]],
    ['БОВ-421102', [...]],
    ['БО-331103', [...]]
]
```

**Вариант 1**. Выведите список студентов конкретной группы построчно виде:

```bash
<Название группы>
<ФИО>
<ФИО>
```


In [22]:
def task631(data):
    for i in range(len(data)):
        group = data[i][0]
        peoples = data[i][1]
        print(group)
        for j in range(len(peoples)):
            print("\t%s" % peoples[j])

def task631_main():
    print(
        """
Задание 6 "Списки"

Пункт 3. Пусть журнал по предмету "Информационные технологии" представлен в виде списка: 

my_len = [
    ['БО-331101', ['Акулова Алена', 'Бабушкина Ксения', ...]],
    ['БОВ-421102', [...]],
    ['БО-331103', [...]]
]

Вариант 1. Выведите список студентов конкретной группы построчно виде:

<Название группы>
    <ФИО>
    <ФИО>
        """
    )

    data = [
        [
            'ПО-4(1)',
            [
                'Андрейчиков Даниил Сергеевич',
                'Байдук Яна Алексеевна',
                'Боровский Максим Витальевич',
                'Воробей Анастасия Петровна',
                'Галанин Павел Иннокентьевич',
                'Грибовский Дмитрий Сергеевич',
                'Грицак Александра Вячеславовна',
                'Елисеев Сергей Геннадьевич',
                'Жук Владислав Алексеевич',
                'Иваненко Иван Леонидович',
                'Калиновский Владимир Евгеньевич',
                'Ковальчук Владислав Владимирович'
            ]
        ],
        [
            'ПО-4(2)',
            [
                'Коташевич Станислав Николаевич',
                'Кречко Кирилл Андреевич',
                'Куделя Алексей Александрович',
                'Луд Алексей Сергеевич',
                'Маевский Александр Васильевич',
                'Пивник Николай Викторович',
                'Прокопюк Никита Олегович',
                'Синяк Данила Анатольевич',
                'Тупик Денис Леонтьевич',
                'Шиба Анастасия Александровна',
                'Юрьев Владислав Александрович',
                'Яковчик Илья Александрович'
            ]
        ]
    ]

    task631(data)

task631_main()


Задание 6 "Списки"

Пункт 3. Пусть журнал по предмету "Информационные технологии" представлен в виде списка: 

my_len = [
    ['БО-331101', ['Акулова Алена', 'Бабушкина Ксения', ...]],
    ['БОВ-421102', [...]],
    ['БО-331103', [...]]
]

Вариант 1. Выведите список студентов конкретной группы построчно виде:

<Название группы>
    <ФИО>
    <ФИО>
        
ПО-4(1)
	Андрейчиков Даниил Сергеевич
	Байдук Яна Алексеевна
	Боровский Максим Витальевич
	Воробей Анастасия Петровна
	Галанин Павел Иннокентьевич
	Грибовский Дмитрий Сергеевич
	Грицак Александра Вячеславовна
	Елисеев Сергей Геннадьевич
	Жук Владислав Алексеевич
	Иваненко Иван Леонидович
	Калиновский Владимир Евгеньевич
	Ковальчук Владислав Владимирович
ПО-4(2)
	Коташевич Станислав Николаевич
	Кречко Кирилл Андреевич
	Куделя Алексей Александрович
	Луд Алексей Сергеевич
	Маевский Александр Васильевич
	Пивник Николай Викторович
	Прокопюк Никита Олегович
	Синяк Данила Анатольевич
	Тупик Денис Леонтьевич
	Шиба Анастасия Александровна
	Ю

## Задание 6 "Списки"

**Пункт 4**. Пусть журнал по предмету "Информационные технологии" представлен в виде списка: 

```python
my_len = [
    ['БО-331101', ['Акулова Алена', 'Бабушкина Ксения', ...]],
    ['БОВ-421102', [...]],
    ['БО-331103', [...]]
]
```

**Вариант 1**. Выведите всех студентов (и их группы), если фамилия студента начинается на букву 'А'.


In [23]:
def task641(data):
    print()
    for i in range(len(data)):
        group = data[i][0]
        peoples = data[i][1]
        for j in range(len(peoples)):
            if peoples[j][0] == 'А':
                print("%32s - %s" % (peoples[j], group))

def task641_main():
    print(
        """
Задание 6 "Списки"

4. Пусть журнал по предмету "Информационные технологии" представлен в виде списка: 

my_len = [
    ['БО-331101', ['Акулова Алена', 'Бабушкина Ксения', ...]],
    ['БОВ-421102', [...]],
    ['БО-331103', [...]]
]

Вариант 1. Выведите всех студентов (и их группы), если фамилия студента начинается на букву 'А'.
        """
    )

    data = [
        [
            'ПО-4(1)',
            [
                'Андрейчиков Даниил Сергеевич',
                'Байдук Яна Алексеевна',
                'Боровский Максим Витальевич',
                'Воробей Анастасия Петровна',
                'Галанин Павел Иннокентьевич',
                'Грибовский Дмитрий Сергеевич',
                'Грицак Александра Вячеславовна',
                'Елисеев Сергей Геннадьевич',
                'Жук Владислав Алексеевич',
                'Иваненко Иван Леонидович',
                'Калиновский Владимир Евгеньевич',
                'Ковальчук Владислав Владимирович'
            ]
        ],
        [
            'ПО-4(2)',
            [
                'Коташевич Станислав Николаевич',
                'Кречко Кирилл Андреевич',
                'Куделя Алексей Александрович',
                'Луд Алексей Сергеевич',
                'Маевский Александр Васильевич',
                'Пивник Николай Викторович',
                'Прокопюк Никита Олегович',
                'Синяк Данила Анатольевич',
                'Тупик Денис Леонтьевич',
                'Шиба Анастасия Александровна',
                'Юрьев Владислав Александрович',
                'Яковчик Илья Александрович'
            ]
        ]
    ]

    task641(data)

task641_main()


Задание 6 "Списки"

4. Пусть журнал по предмету "Информационные технологии" представлен в виде списка: 

my_len = [
    ['БО-331101', ['Акулова Алена', 'Бабушкина Ксения', ...]],
    ['БОВ-421102', [...]],
    ['БО-331103', [...]]
]

Вариант 1. Выведите всех студентов (и их группы), если фамилия студента начинается на букву 'А'.
        

    Андрейчиков Даниил Сергеевич - ПО-4(1)


## Задание 7 "Функции"

1. Реализуйте задания предыдущих лабораторных работ (выполненные согласно вашему варианту) в виде пользовательских функций.

2. Реализуйте единое пользовательское меню выбора соответствующих функций из задания №1 в виде:

    ```bash
0 - Выход из программы
1 - Название функции №1
2 - Название функции №2
3 - ...
    ```

    После выполнения каждой из функций запрашивайте у пользователя 'Вы хотите продолжить?'. Если ответ 'да' (yes, Y, I), то снова выводите меню. Если ответ 'нет' (no, N, 0), то завершите программу.

In [24]:
import os

# from task_1_1_1 import task111_main
# from task_1_2_1 import task121_main
# from task_1_3_1 import task131_main
# from task_1_4_1 import task141_main

# from task_2_1_1 import task211_main
# from task_2_2_1 import task221_main
# from task_2_3_1 import task231_main
# from task_2_4_1 import task241_main

# from task_3_1_1 import task311_main
# from task_3_2_1 import task321_main
# from task_3_4_1 import task341_main
# from task_3_5_3 import task353_main
# from task_3_6_3 import task363_main
# from task_3_7_3 import task373_main
# from task_3_8_1 import task381_main

# from task_4_1_1 import task411_main
# from task_4_2_1 import task421_main
# from task_4_3_1 import task431_main
# from task_4_4   import task44_main

# from task_6_1   import task61_main
# from task_6_2_1 import task621_main
# from task_6_3_1 import task631_main
# from task_6_4_1 import task641_main

def cls():
    os.system('cls' if os.name=='nt' else 'clear')

def pause():
    print('Press any key to continue...')
    string = input()

def menu():
    cls()
    print(
        """
1. Задание 1
2. Задание 2
3. Задание 3
4. Задание 4
6. Задание 6
0. Выход из из программы
        """
    )
    case = input() # запись строки
    case = case[0] # взятие первого символа со строки
    case = ord(case) # перевод символа в число

    if case == ord('0'):
        return

    elif case == ord('1'):
        sum_menu_1()
        menu()

    elif case == ord('2'):
        sum_menu_2()
        menu()

    elif case == ord('3'):
        sum_menu_3()
        menu()

    elif case == ord('4'):
        sum_menu_4()
        menu()

    elif case == ord('6'):
        sum_menu_6()
        menu()

    else:
        menu()

def sum_menu_1():
    cls()
    print(
    """
1. 111
2. 121
3. 131
4. 141
0. Выход в главное меню
    """
    )

    case = input() # запись строки
    case = case[0] # взятие первого символа со строки
    case = ord(case) # перевод символа в число

    cls()

    if case == ord('0'):
        return

    elif case == ord('1'):
        task111_main()

    elif case == ord('2'):
        task121_main()

    elif case == ord('3'):
        task131_main()

    elif case == ord('4'):
        task141_main() 

    else:
        return

    pause()

def sum_menu_2():
    cls()
    print(
    """
1. 211
2. 221
3. 231
4. 241
0. Выход в главное меню
    """
    )

    case = input() # запись строки
    case = case[0] # взятие первого символа со строки
    case = ord(case) # перевод символа в число

    cls()

    if case == ord('0'):
        return

    elif case == ord('1'):
        task211_main()

    elif case == ord('2'):
        task221_main()

    elif case == ord('3'):
        task231_main()

    elif case == ord('4'):
        task241_main()

    else:
        return

    pause()

def sum_menu_3():
    cls()
    print(
    """
1. 311
2. 321
4. 341
5. 353
6. 363
7. 373
8. 381
0. Выход в главное меню
    """
    )

    case = input() # запись строки
    case = case[0] # взятие первого символа со строки
    case = ord(case) # перевод символа в число

    cls()

    if case == ord('0'):
        return

    elif case == ord('1'):
        task311_main()

    elif case == ord('2'):
        task321_main()

    elif case == ord('4'):
        task341_main()

    elif case == ord('5'):
        task353_main()
        
    elif case == ord('6'):
        task363_main()

    elif case == ord('7'):
        task373_main()

    elif case == ord('8'):
        task381_main()

    else:
        return

    pause()

def sum_menu_4():
    cls()
    print(
    """
1. 411
2. 421
3. 431
4. 44
0. Выход в главное меню
    """
    )

    case = input() # запись строки
    case = case[0] # взятие первого символа со строки
    case = ord(case) # перевод символа в число

    cls()

    if case == ord('0'):
        return

    elif case == ord('1'):
        task411_main()

    elif case == ord('2'):
        task421_main()

    elif case == ord('3'):
        task431_main()

    elif case == ord('4'):
        task44_main()

    else:
        return

    pause()

def sum_menu_6():
    cls()
    print(
    """
1. 61
2. 62
3. 63
4. 64
0. Выход в главное меню
    """
    )

    case = input() # запись строки
    case = case[0] # взятие первого символа со строки
    case = ord(case) # перевод символа в число

    cls()

    if case == ord('0'):
        return

    elif case == ord('1'):
        task61_main()

    elif case == ord('2'):
        task621_main()

    elif case == ord('3'):
        task631_main()

    elif case == ord('4'):
        task641_main()

    else:
        return

    pause()

menu()


1. Задание 1
2. Задание 2
3. Задание 3
4. Задание 4
6. Задание 6
0. Выход из из программы
        
0


Вывод: "".