# Лабораторная работа №4

**Цель работы**: "".

**Ход работы**:

---

## Задание 1

**Пункт 1**. Напишите программу для решения примера (по вариантам). Предусмотрите проверку деления на ноль. Все необходимые переменные пользователь вводит через консоль. Запись |пример| означает <<взять по модулю>>, т. е. если значение получится отрицательным, необходимо сменить знак с минуса на плюс.

**Вариант 1**. $|{ {({a^2 \over b^2} + c^2 \cdot a^2)} \over {(a + b + c \cdot (k- {a \over b^3}))} } + c + ({k \over b} - {k \over a}) \cdot c|$

In [1]:
import math

def task111(a, b, c, k):
    if a == 0:
        print("a = 0. Error: div on zero")
        return -1
    elif b == 0:
        print("b = 0. Error: div on zero")
        return -1
    else:
        part1 = math.pow(a, 2) / math.pow(b, 2) + math.pow(c, 2) * math.pow(a, 2)
        part2 = a + b + c * (k - a / math.pow(b, 3))
        part3 = c + (k/b - k/a) * c
        result = part1 + part2 + part3
        if result >= 0:
            return result
        else:
            return -result

print(task111(0,1,1,1))
print(task111(1,0,1,1))
print(task111(1,1,1,1))

a = 0. Error: div on zero
-1
b = 0. Error: div on zero
-1
5.0


---

## Задание 1

**Пункт 2**. Дан произвольный список, содержащий и строки и числа.

**Вариант 1**. Выведите все четные элементы построчно.

In [2]:
def task121(lst):
    for i in range(len(lst)):
        if (i + 1) % 2 == 0:
            print(lst[i])
            
lst = ['33', 2, 4, 5.3, 2.4, 5555.3, '443', 'ergr', 'wee', 'efe']

task121(lst)

2
5.3
5555.3
ergr
efe


---

## Задание 1

**Пункт 3**. Дан произвольный список, содержащий только числа.

**Вариант 1**. Выведите результат сложения всех чисел больше 10.

In [3]:
def task131(lst):
    sum = 0
    for i in range(len(lst)):
        if lst[i] > 10:
            sum += lst[i]
    print(sum)
    
lst = [-10, 5, 6, 15, 3, 16, 7]

task131(lst)

31


---

## Задание 1

**Пункт 4**. Дан произвольный список, содержащий только числа.

**Вариант 1**. Выведите максимальное число.

In [4]:
def task141(lst):
    max = lst[0]
    for i in range(len(lst)):
        if lst[i] > max:
            max = lst[i]
    print(max)
    
lst = [4, 7, 2, -100, 3, 55, 33, 6]

task141(lst)

55


---

## Задание 2 <<Строки и списки>>

**Пункт 1**. Пусть задано некоторое число my number. Пользователь вводит с клавиатуры свое число user_number.

**Вариант 1**. Запрашивайте у пользователя вводить число user number до тех пор, пока оно не будет меньше my_number.

In [5]:
def task211():
    my_number = 5
    while 1:
        user_number = int(input("user_number := "))
        if user_number < my_number:
            break
            
task211()

user_number := 77
user_number := 55
user_number := 5
user_number := 2


---

## Задание 2 <<Строки и списки>>

**Пункт 2**. Пусть задан список, содержащий строки.

**Вариант 1**. Выведите построчно все строки размером от 5 до 10 символов.

In [6]:
def task221(lst):
    for i in range(len(lst)):
        length = len(lst[i])
        if 5 < length and length < 10:
            print(lst[i])
            
lst = [
    'aaa',
    'bbbbbb',
    'ccccc',
    'dddddddddd',
    'eeeeeeeee'
]

task221(lst)

bbbbbb
eeeeeeeee


---

## Задание 2 <<Строки и списки>>

**Пункт 3**. Сгенерируйте и выведите:

**Вариант 1**. Случайную строку, состоящую из 5 символов, содержащую только заглавные буквы русского алфавита.

In [7]:
import random

def task231():
    result = ''
    for i in range(5):
        number = random.randint(65, 90)
        symbol = chr(number)
        result += symbol
    return result

print(task231())

XFGKP


---

## Задание 2 <<Строки и списки>>

**Пункт 4**. Пусть дана строка:

**Вариант 1**. На основе данной строки сформируйте новую, содержащую только цифры. Выведите новую строку.


In [8]:
def task241(string):
    strWithNum = ''
    for i in range(len(string)):
        number = ord(string[i])
        temp = str(number)
        strWithNum += temp
    return strWithNum
        
print(task241('qwerty'))

113119101114116121


---

## Задание 3 <<Матрицы>>

Пусть дана матрица:

```
1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2
```

**Вариант №1**. Определите структуру для хранения матрицы.

**Пункт 1**. Напишите функцию возведения всех элементов матрицы в квадрат.


In [9]:
import math
import numpy

def task311(arr):
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            arr[i][j] = math.pow(arr[i][j], 2)
 
arr = numpy.array([
    [1, 2, 3, 4, 5, 6, 7, 8],
    [8, 7, 6, 5, 4, 3, 2, 1],
    [2, 3, 4, 5, 6, 7, 8, 9],
    [9, 8, 7, 6, 5, 4, 3, 2],
    [1, 3, 5, 7, 9, 7, 5, 3],
    [3, 1, 5, 3, 2, 6, 5, 7],
    [1, 7, 5, 9, 7, 3, 1, 5],
    [2, 6, 3, 5, 1, 7, 3, 2]
])

print(arr)
task311(arr)
print(arr)


[[1 2 3 4 5 6 7 8]
 [8 7 6 5 4 3 2 1]
 [2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2]
 [1 3 5 7 9 7 5 3]
 [3 1 5 3 2 6 5 7]
 [1 7 5 9 7 3 1 5]
 [2 6 3 5 1 7 3 2]]
[[ 1  4  9 16 25 36 49 64]
 [64 49 36 25 16  9  4  1]
 [ 4  9 16 25 36 49 64 81]
 [81 64 49 36 25 16  9  4]
 [ 1  9 25 49 81 49 25  9]
 [ 9  1 25  9  4 36 25 49]
 [ 1 49 25 81 49  9  1 25]
 [ 4 36  9 25  1 49  9  4]]


---

## Задание 3 <<Матрицы>>

Пусть дана матрица:

```
1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2
```

**Вариант №2**. Определите структуру для хранения матрицы.

**Пункт 1.** Напишите функцию сложения по строкам.


In [10]:
def task321(arr):
    for i in range(len(arr)):
        sum = 0
        for j in range(len(arr[i])):
            sum += arr[i][j]
            print("%4d\t" % arr[i][j], end = '')
        print(sum)
        
arr = [
    [1, 2, 3, 4, 5, 6, 7, 8],
    [8, 7, 6, 5, 4, 3, 2, 1],
    [2, 3, 4, 5, 6, 7, 8, 9],
    [9, 8, 7, 6, 5, 4, 3, 2],
    [1, 3, 5, 7, 9, 7, 5, 3],
    [3, 1, 5, 3, 2, 6, 5, 7],
    [1, 7, 5, 9, 7, 3, 1, 5],
    [2, 6, 3, 5, 1, 7, 3, 2]
]

task321(arr)

   1	   2	   3	   4	   5	   6	   7	   8	36
   8	   7	   6	   5	   4	   3	   2	   1	36
   2	   3	   4	   5	   6	   7	   8	   9	44
   9	   8	   7	   6	   5	   4	   3	   2	44
   1	   3	   5	   7	   9	   7	   5	   3	40
   3	   1	   5	   3	   2	   6	   5	   7	32
   1	   7	   5	   9	   7	   3	   1	   5	38
   2	   6	   3	   5	   1	   7	   3	   2	29


---

## Задание 3 <<Матрицы>>

Пусть дана матрица:

```
1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2
```

**Вариант №4**. Определите структуру для хранения матрицы.

**Пункт 1.** Напишите функцию умножения по строкам.


In [11]:
def task341(arr):
    for i in range(len(arr)):
        mult = 1
        for j in range(len(arr[i])):
            mult *= arr[i][j]
            print("%4d\t" % arr[i][j], end = '')
        print(mult)
        
arr = [
    [1, 2, 3, 4, 5, 6, 7, 8],
    [8, 7, 6, 5, 4, 3, 2, 1],
    [2, 3, 4, 5, 6, 7, 8, 9],
    [9, 8, 7, 6, 5, 4, 3, 2],
    [1, 3, 5, 7, 9, 7, 5, 3],
    [3, 1, 5, 3, 2, 6, 5, 7],
    [1, 7, 5, 9, 7, 3, 1, 5],
    [2, 6, 3, 5, 1, 7, 3, 2]
]

task341(arr)   

   1	   2	   3	   4	   5	   6	   7	   8	40320
   8	   7	   6	   5	   4	   3	   2	   1	40320
   2	   3	   4	   5	   6	   7	   8	   9	362880
   9	   8	   7	   6	   5	   4	   3	   2	362880
   1	   3	   5	   7	   9	   7	   5	   3	99225
   3	   1	   5	   3	   2	   6	   5	   7	18900
   1	   7	   5	   9	   7	   3	   1	   5	33075
   2	   6	   3	   5	   1	   7	   3	   2	7560


---

## Задание 3 <<Матрицы>>

Пусть дана матрица:

```
1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2
```

**Вариант №5**. Определите структуру для хранения матрицы.

**Пункт 3**. Напишите функцию возведения всех чисел 5 в квадрат.

In [12]:
import numpy

def task353(arr):
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            if arr[i][j] == 5:
                arr[i][j] = 25
                
arr = numpy.array([
    [1, 2, 3, 4, 5, 6, 7, 8],
    [8, 7, 6, 5, 4, 3, 2, 1],
    [2, 3, 4, 5, 6, 7, 8, 9],
    [9, 8, 7, 6, 5, 4, 3, 2],
    [1, 3, 5, 7, 9, 7, 5, 3],
    [3, 1, 5, 3, 2, 6, 5, 7],
    [1, 7, 5, 9, 7, 3, 1, 5],
    [2, 6, 3, 5, 1, 7, 3, 2]
])

print(arr)
task353(arr)
print(arr)

[[1 2 3 4 5 6 7 8]
 [8 7 6 5 4 3 2 1]
 [2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2]
 [1 3 5 7 9 7 5 3]
 [3 1 5 3 2 6 5 7]
 [1 7 5 9 7 3 1 5]
 [2 6 3 5 1 7 3 2]]
[[ 1  2  3  4 25  6  7  8]
 [ 8  7  6 25  4  3  2  1]
 [ 2  3  4 25  6  7  8  9]
 [ 9  8  7  6 25  4  3  2]
 [ 1  3 25  7  9  7 25  3]
 [ 3  1 25  3  2  6 25  7]
 [ 1  7 25  9  7  3  1 25]
 [ 2  6  3 25  1  7  3  2]]


---

## Задание 3 <<Матрицы>>

Пусть дана матрица:

```
1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2
```

**Вариант №6**. Определите структуру для хранения матрицы.

**Пункт 3**. Напишите функцию очистки матрицы.


In [13]:
import numpy

def task363(arr):
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            arr[i][j] = 0
            
arr = numpy.array([
    [1, 2, 3, 4, 5, 6, 7, 8],
    [8, 7, 6, 5, 4, 3, 2, 1],
    [2, 3, 4, 5, 6, 7, 8, 9],
    [9, 8, 7, 6, 5, 4, 3, 2],
    [1, 3, 5, 7, 9, 7, 5, 3],
    [3, 1, 5, 3, 2, 6, 5, 7],
    [1, 7, 5, 9, 7, 3, 1, 5],
    [2, 6, 3, 5, 1, 7, 3, 2]
])

print(arr)
task363(arr)
print(arr)

[[1 2 3 4 5 6 7 8]
 [8 7 6 5 4 3 2 1]
 [2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2]
 [1 3 5 7 9 7 5 3]
 [3 1 5 3 2 6 5 7]
 [1 7 5 9 7 3 1 5]
 [2 6 3 5 1 7 3 2]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


---

## Задание 3 <<Матрицы>>

Пусть дана матрица:

```
1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2
```

**Вариант №7**. Определите структуру для хранения матрицы.

**Пункт 3**. Напишите функцию, которая посчитает, сколько раз в матрице встречается число 3


In [14]:
import numpy

def task373(arr):
    sum = 0
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            if arr[i][j] == 3:
                sum += 1
    return sum

arr = numpy.array([
    [1, 2, 3, 4, 5, 6, 7, 8],
    [8, 7, 6, 5, 4, 3, 2, 1],
    [2, 3, 4, 5, 6, 7, 8, 9],
    [9, 8, 7, 6, 5, 4, 3, 2],
    [1, 3, 5, 7, 9, 7, 5, 3],
    [3, 1, 5, 3, 2, 6, 5, 7],
    [1, 7, 5, 9, 7, 3, 1, 5],
    [2, 6, 3, 5, 1, 7, 3, 2]
])

print(arr)

print(task373(arr))

[[1 2 3 4 5 6 7 8]
 [8 7 6 5 4 3 2 1]
 [2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2]
 [1 3 5 7 9 7 5 3]
 [3 1 5 3 2 6 5 7]
 [1 7 5 9 7 3 1 5]
 [2 6 3 5 1 7 3 2]]
11


---

## Задание 3 <<Матрицы>>

Пусть дана матрица:

```
1 2 3 4 5 6 7 8
8 7 6 5 4 3 2 1
2 3 4 5 6 7 8 9
9 8 7 6 5 4 3 2
1 3 5 7 9 7 5 3
3 1 5 3 2 6 5 7
1 7 5 9 7 3 1 5
2 6 3 5 1 7 3 2
```

**Вариант №8**. Определите структуру для хранения матрицы.

**Пункт 1**. Пусть пользователь через консоль вводит два числа: первое - номер строки, второе - номер столбца. Напишите функцию, которая найдет число в данной позиции.


In [15]:
import numpy

def task381(arr, i, j):
    if i > len(arr):
        return 0
    elif j > len(arr[i]):
        return 0
    else:
        return arr[i - 1][j - 1]

arr = numpy.array([
    [1, 2, 3, 4, 5, 6, 7, 8],
    [8, 7, 6, 5, 4, 3, 2, 1],
    [2, 3, 4, 5, 6, 7, 8, 9],
    [9, 8, 7, 6, 5, 4, 3, 2],
    [1, 3, 5, 7, 9, 7, 5, 3],
    [3, 1, 5, 3, 2, 6, 5, 7],
    [1, 7, 5, 9, 7, 3, 1, 5],
    [2, 6, 3, 5, 1, 7, 3, 2]
])

print(arr)

print(task381(arr, -3, -3))
print(task381(arr, -2, -2))
print(task381(arr, -1, -1))
print(task381(arr, 0, 0))
print()
print(task381(arr, 4, 4))
print(task381(arr, 40, 4))
print(task381(arr, 4, 40))

[[1 2 3 4 5 6 7 8]
 [8 7 6 5 4 3 2 1]
 [2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2]
 [1 3 5 7 9 7 5 3]
 [3 1 5 3 2 6 5 7]
 [1 7 5 9 7 3 1 5]
 [2 6 3 5 1 7 3 2]]
9
6
1
2

6
0
0


Вывод: "".